name: Test rpy2

on:
  push:
    branches:
      - '**'

jobs:
  test_rpy2:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - {name: '3.9', os: ubuntu-latest, python: '3.9', r: 'devel' }
        - {name: '3.8', os: ubuntu-latest, python: '3.8', r: 'release' }
        - {name: '3.7', os: ubuntu-latest, python: '3.7', r: 'release' }
        - {name: '3.7', os: ubuntu-latest, python: '3.7', r: 'none' }
        - {name: '3.6', os: ubuntu-latest, python: '3.6', r: 'oldrel' }

    steps:

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.config.python }}

    - name: Set up R
      id: setup-r
      if: ${{ matrix.config.r != 'none' }}
      uses: r-lib/actions/setup-r@master
      with:
        r-version: ${{ matrix.config.r }}

    - name: Test rpy2
      run: |
        python -m venv pyenv_base
        source pyenv_base/bin/activate
        python -m pip install -U pip wheel
        python -m pip install git+https://github.com/rpy2/rpy2
        export LD_LIBRARY_PATH=$(python -m rpy2.situation LD_LIBRARY_PATH):${LD_LIBRARY_PATH}
        python -c "import rpy2.robjects"

    - name: Print system config
      if: always()
      shell: /usr/bin/env bash -ex {0}
      run: |
        uname -a
        python --version
        R --version
        python -m pip freeze