name: Test rpy2

on:
  push:
    branches:
      - '**'

jobs:
  test_rpy2:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - {name: 'devel_v1_with_ld', r: 'devel', os: ubuntu-latest, python: '3.9', setup_python: 'v1', set_ld_library_path: true}
        - {name: 'devel_v2_with_ld', r: 'devel', os: ubuntu-latest, python: '3.9', setup_python: 'v2', set_ld_library_path: true}
        - {name: 'devel_v1', r: 'devel', os: ubuntu-latest, python: '3.9', setup_python: 'v1', set_ld_library_path: false}
        - {name: 'devel_v2', r: 'devel', os: ubuntu-latest, python: '3.9', setup_python: 'v2', set_ld_library_path: false}
        - {name: 'release_v1_with_ld', r: 'release', os: ubuntu-latest, python: '3.8', setup_python: 'v1', set_ld_library_path: true}
        - {name: 'release_v2_with_ld', r: 'release', os: ubuntu-latest, python: '3.8', setup_python: 'v2', set_ld_library_path: true}
        - {name: 'release_v1', r: 'release', os: ubuntu-latest, python: '3.8', setup_python: 'v1', set_ld_library_path: false}
        - {name: 'release_v2', r: 'release', os: ubuntu-latest, python: '3.8', setup_python: 'v2', set_ld_library_path: false}
        - {name: 'oldrel_v1_with_ld', r: 'oldrel', os: ubuntu-latest, python: '3.7',  setup_python: 'v1', set_ld_library_path: true}
        - {name: 'oldrel_v2_with_ld', r: 'oldrel', os: ubuntu-latest, python: '3.7',  setup_python: 'v2', set_ld_library_path: true}
        - {name: 'oldrel_v1', r: 'oldrel', os: ubuntu-latest, python: '3.7',  setup_python: 'v1', set_ld_library_path: false}
        - {name: 'oldrel_v2', r: 'oldrel', os: ubuntu-latest, python: '3.7',  setup_python: 'v2', set_ld_library_path: false}

    steps:

    - name: Set up Python
      uses: actions/setup-python@${{ matrix.config.setup_python }}
      with:
        python-version: ${{ matrix.config.python }}

    - name: Set up R
      id: setup-r
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.config.r }}

    - name: Install rpy2
      run: |
        python -m pip install -U pip wheel
        python -m pip install rpy2

    - name: Set LD_LIBRARY_PATH
      if: ${{ matrix.config.set_ld_library_path }}
      run: echo "LD_LIBRARY_PATH=$(python -m rpy2.situation LD_LIBRARY_PATH):${LD_LIBRARY_PATH}" >> $GITHUB_ENV

    - name: Import rpy2
      run: |
        python -c "import rpy2.robjects"

    - name: Print system config
      if: always()
      shell: /usr/bin/env bash -ex {0}
      run: |
        uname -a
        python --version
        R --version
        python -m pip freeze