name: Test rpy2

on:
  push:
    branches:
      - '**'

jobs:
  test_rpy2:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - {name: '3.9', os: ubuntu-latest, python: '3.9', r: 'devel' }
        - {name: '3.8', os: ubuntu-latest, python: '3.8', r: 'release' }
        - {name: '3.7', os: ubuntu-latest, python: '3.7', r: 'release' }
        - {name: '3.6', os: ubuntu-latest, python: '3.6', r: 'oldrel' }

    steps:

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.python }}

    - name: Set up R
      id: setup-r
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.config.r }}

    - name: Test rpy2
      run: |
        pip install wheel
        pip install rpy2
        python -c "import rpy2"
        echo done
        python -c "import rpy2.robjects"
        echo done
        python -c "from rpy2.robjects import conversion"
